name: "Adam Malone Site"
machine: "adammalone_net"
environments:
  prod:
    server: "poseidon"
    path: "/var/www/html/adammalone_net"
  test:
    server: "hermes"
    path: "/var/www/html/adammalone_net"