name: "My Example Site"
machine: "example_docroot"
environments:
  prod:
    server: "example_server"
    path: "/var/www/html/example_docroot/docroot"
    uri: "example.com"
  test:
    server: "other_example"
    path: "/var/www/html/example_docroot/docroot"
    uri: "dev.example.com"
