name: "Stalkerspace"
machine: "stalkerspace_com"
environments:
  prod:
    server: "poseidon"
    path: "/var/www/html/stalkerspace_com"
  test:
    server: "hermes"
    path: "/var/www/html/stalkerspace_com"